name: Test Workflow

on: [push]

jobs:
  info_linux_ubuntu:
    name: Info Linux Ubuntu
    runs-on: [ubuntu-latest]
    steps:
      - name: Core Environment
        run: |
          echo "Hello, world!"
          echo "Current directory: $PWD"
          echo "Current branch: $GITHUB_REF"
          echo "Current commit: $GITHUB_SHA"
          echo "Current job: $GITHUB_JOB"
          echo "Current step: $GITHUB_STEP_SUMMARY"
      - name: Regular Environment
        run: env | sort
        
  info_windows:
    name: Info Windows
    runs-on: windows-latest
    steps:
      - name: Core Environment
        run: |
          Write-Host "Hello, world!"
          Write-Host "Current directory: $($PWD.Path)"
          Write-Host "Current branch: $env:GITHUB_REF"
          Write-Host "Current commit: $env:GITHUB_SHA"
          Write-Host "Current job: $env:GITHUB_JOB"
          Write-Host "Current step: $env:GITHUB_STEP_SUMMARY"
      - name: Regular Environment
        run: "Get-ChildItem Env: | Sort-Object Name"  

  info_macos:
    name: Info MacOS
    runs-on: macos-latest
    steps:
      - name: Core Environment
        run: |
          echo "Hello, world!"
          echo "Current directory: $PWD"
          echo "Current branch: $GITHUB_REF"
          echo "Current commit: $GITHUB_SHA"
          echo "Current job: $GITHUB_JOB"
          echo "Current step: $GITHUB_STEP_SUMMARY"
      - name: Regular Environment
        run: "env | sort" 

  final_job:
    name: Final Job
    runs-on: [ubuntu-latest]
    needs: [info_linux_ubuntu, info_windows, info_macos]
    steps:
      - name: Final Step
        run: echo "Final job completed"

